name: Build MacOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - name: zip macos artifact
      run: |
        zip -r macos out 
    - name: upload macos artifact
      uses: actions/upload-artifact@v1
      with:
        name: uploads
        path: macos.zip                    
